### ISSUE TITLE
Ping about https://github.com/nodejs/node/pull/20876

### ISSUE THREAD

**Issue by benjamingr** [nodejs/worker#5]
Hey, pinging people who have watched this repo about addaleax's impressive PR at https://github.com/nodejs/node/pull/20876 

This is about a year of her effort - you can see the previous work and reviews [here](https://github.com/ayojs/ayo/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+worker) if interested.

Would be great to get more eyes and reviews on that PR so we can figure out how to ship it.

**Comment by addaleax** [comment]
I’m closing the existing issues here. If you have feedback about the existing Workers implementation in Node.js 10+, please use https://github.com/nodejs/worker/issues/6 for that!
